name: Deploy all services

on:
  push: [main]

jobs:
  cd-job:
    runs-on: self-hosted
    steps:
      - name: Pull updates
        run: git pull
        working-directory: $HOME/project/deploy

      - name: Up services
        run: docker compose up -d
        working-directory: $HOME/project/deploy


